"""Core Pydantic data schemas for the Multimodal Financial Intelligence RAG system."""

import uuid
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union
from pydantic import BaseModel, Field


class ElementType(str, Enum):
    """Document element types extracted from financial documents."""

    TEXT = "text"
    TABLE = "table"
    CHART = "chart"
    IMAGE = "image"


class BoundingBox(BaseModel):
    """Bounding box coordinates (normalized or PDF points) for an extracted element."""

    x0: float = Field(..., description="Left coordinate")
    y0: float = Field(..., description="Top coordinate")
    x1: float = Field(..., description="Right coordinate")
    y1: float = Field(..., description="Bottom coordinate")

    def to_tuple(self) -> Tuple[float, float, float, float]:
        """Return coordinates as (x0, y0, x1, y1) tuple."""
        return (self.x0, self.y0, self.x1, self.y1)


class DocumentElement(BaseModel):
    """Core representation of an extracted element from a financial filing.

    Represents textual narrative, financial tables, charts, or images
    extracted from 10-Ks, annual reports, and earnings decks.
    """

    element_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the document element",
    )
    doc_name: str = Field(
        ...,
        description="Source document name or filename (e.g., 'AAPL_2023_10K.pdf')",
    )
    page_number: int = Field(
        ...,
        ge=1,
        description="1-based page number where the element appears in the document",
    )
    element_type: ElementType = Field(
        ...,
        description="Element classification: text, table, chart, or image",
    )
    content: str = Field(
        ...,
        description=(
            "Primary content payload: narrative text, markdown-formatted table, "
            "or Gemini multimodal structured description of a chart/image"
        ),
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Domain-specific metadata (ticker, fiscal year, statement type, metric names, etc.)",
    )
    bbox: Optional[Union[BoundingBox, Tuple[float, float, float, float], List[float]]] = Field(
        default=None,
        description="Bounding box coordinates on the page (x0, y0, x1, y1)",
    )


class Citation(BaseModel):
    """Traceable citation linking a response back to the source document element."""

    element_id: str = Field(..., description="ID of the cited DocumentElement")
    doc_name: str = Field(..., description="Source document name")
    page_number: int = Field(..., description="Source document page number")
    element_type: Optional[ElementType] = Field(
        default=None,
        description="Type of the cited element",
    )
    snippet: Optional[str] = Field(
        default=None,
        description="Relevant text excerpt or summary cited in the answer",
    )
    bbox: Optional[Union[BoundingBox, Tuple[float, float, float, float], List[float]]] = Field(
        default=None,
        description="Visual bounding box of the citation for UI highlighting",
    )


class QueryResult(BaseModel):
    """Result model containing the synthesized answer, citations, and retrieved elements."""

    answer: str = Field(
        ...,
        description="Synthesized financial analysis answer generated by the Gemini model",
    )
    citations: List[Citation] = Field(
        default_factory=list,
        description="List of grounded citations supporting statements in the answer",
    )
    retrieved_elements: List[DocumentElement] = Field(
        default_factory=list,
        description="List of retrieved DocumentElements utilized in generating the answer",
    )
